# Generated by Django 4.2.13 on 2024-06-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_start_of_work',
        ),
        migrations.CreateModel(
            name='Teacher_to_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Schadule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.subject')),
            ],
        ),
    ]
